version: '3.1'

services: 
  db:
    image: postgres:12
    container_name: "NoteApp"
    env_file: 
      - database.env
    ports: 
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
  
volumes: 
  db-data: